// Code generated by protoc-gen-go.
// source: fight.proto
// DO NOT EDIT!

package protomsg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Vector2 struct {
	X                *float32 `protobuf:"fixed32,1,req,name=x" json:"x,omitempty"`
	Y                *float32 `protobuf:"fixed32,2,req,name=y" json:"y,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Vector2) Reset()                    { *m = Vector2{} }
func (m *Vector2) String() string            { return proto.CompactTextString(m) }
func (*Vector2) ProtoMessage()               {}
func (*Vector2) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Vector2) GetX() float32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *Vector2) GetY() float32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

type AOI struct {
	// 时间戳
	Time *int64 `protobuf:"varint,1,req,name=time" json:"time,omitempty"`
	// 位置
	Pos *Vector2 `protobuf:"bytes,2,req,name=pos" json:"pos,omitempty"`
	// 速度
	V                *Vector2 `protobuf:"bytes,3,req,name=v" json:"v,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *AOI) Reset()                    { *m = AOI{} }
func (m *AOI) String() string            { return proto.CompactTextString(m) }
func (*AOI) ProtoMessage()               {}
func (*AOI) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *AOI) GetTime() int64 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *AOI) GetPos() *Vector2 {
	if m != nil {
		return m.Pos
	}
	return nil
}

func (m *AOI) GetV() *Vector2 {
	if m != nil {
		return m.V
	}
	return nil
}

type AOIPushItem struct {
	Entityid         *string `protobuf:"bytes,1,req,name=entityid" json:"entityid,omitempty"`
	Ms               *AOI    `protobuf:"bytes,2,req,name=ms" json:"ms,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AOIPushItem) Reset()                    { *m = AOIPushItem{} }
func (m *AOIPushItem) String() string            { return proto.CompactTextString(m) }
func (*AOIPushItem) ProtoMessage()               {}
func (*AOIPushItem) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *AOIPushItem) GetEntityid() string {
	if m != nil && m.Entityid != nil {
		return *m.Entityid
	}
	return ""
}

func (m *AOIPushItem) GetMs() *AOI {
	if m != nil {
		return m.Ms
	}
	return nil
}

type SpawnState struct {
	// 实体类型
	Type *int32 `protobuf:"varint,1,req,name=type" json:"type,omitempty"`
	// 实体id
	Entityid *string `protobuf:"bytes,2,req,name=entityid" json:"entityid,omitempty"`
	// 时间状态、位置状态
	Ms *AOI `protobuf:"bytes,3,req,name=ms" json:"ms,omitempty"`
	// 资源配置表id
	ResId *int32 `protobuf:"varint,4,opt,name=resId" json:"resId,omitempty"`
	// 用户实体对应的整型用户id
	UserId           *int32 `protobuf:"varint,5,opt,name=userId" json:"userId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SpawnState) Reset()                    { *m = SpawnState{} }
func (m *SpawnState) String() string            { return proto.CompactTextString(m) }
func (*SpawnState) ProtoMessage()               {}
func (*SpawnState) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *SpawnState) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *SpawnState) GetEntityid() string {
	if m != nil && m.Entityid != nil {
		return *m.Entityid
	}
	return ""
}

func (m *SpawnState) GetMs() *AOI {
	if m != nil {
		return m.Ms
	}
	return nil
}

func (m *SpawnState) GetResId() int32 {
	if m != nil && m.ResId != nil {
		return *m.ResId
	}
	return 0
}

func (m *SpawnState) GetUserId() int32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

// 创建战斗请求2100
type CreateFightReq struct {
	Fightid          *string `protobuf:"bytes,1,req,name=fightid" json:"fightid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateFightReq) Reset()                    { *m = CreateFightReq{} }
func (m *CreateFightReq) String() string            { return proto.CompactTextString(m) }
func (*CreateFightReq) ProtoMessage()               {}
func (*CreateFightReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *CreateFightReq) GetFightid() string {
	if m != nil && m.Fightid != nil {
		return *m.Fightid
	}
	return ""
}

// 创建战斗返回2101
type CreateFightAck struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CreateFightAck) Reset()                    { *m = CreateFightAck{} }
func (m *CreateFightAck) String() string            { return proto.CompactTextString(m) }
func (*CreateFightAck) ProtoMessage()               {}
func (*CreateFightAck) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

// 加入战斗请求2102
type JoinFightReq struct {
	// 战斗id
	Fightid *string `protobuf:"bytes,1,req,name=fightid" json:"fightid,omitempty"`
	// 玩家阵营
	Type             *int32 `protobuf:"varint,2,req,name=type" json:"type,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *JoinFightReq) Reset()                    { *m = JoinFightReq{} }
func (m *JoinFightReq) String() string            { return proto.CompactTextString(m) }
func (*JoinFightReq) ProtoMessage()               {}
func (*JoinFightReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *JoinFightReq) GetFightid() string {
	if m != nil && m.Fightid != nil {
		return *m.Fightid
	}
	return ""
}

func (m *JoinFightReq) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

// 加入战斗返回2103
type JoinFightAck struct {
	Spawns           []*SpawnState `protobuf:"bytes,1,rep,name=spawns" json:"spawns,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *JoinFightAck) Reset()                    { *m = JoinFightAck{} }
func (m *JoinFightAck) String() string            { return proto.CompactTextString(m) }
func (*JoinFightAck) ProtoMessage()               {}
func (*JoinFightAck) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *JoinFightAck) GetSpawns() []*SpawnState {
	if m != nil {
		return m.Spawns
	}
	return nil
}

// 推送的加入战斗的玩家2104
type JoinFightPush struct {
	Spawn            *SpawnState `protobuf:"bytes,1,req,name=spawn" json:"spawn,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *JoinFightPush) Reset()                    { *m = JoinFightPush{} }
func (m *JoinFightPush) String() string            { return proto.CompactTextString(m) }
func (*JoinFightPush) ProtoMessage()               {}
func (*JoinFightPush) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *JoinFightPush) GetSpawn() *SpawnState {
	if m != nil {
		return m.Spawn
	}
	return nil
}

// 移动请求2105
type MoveReq struct {
	Pos              *Vector2 `protobuf:"bytes,3,req,name=pos" json:"pos,omitempty"`
	V                *Vector2 `protobuf:"bytes,4,req,name=v" json:"v,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *MoveReq) Reset()                    { *m = MoveReq{} }
func (m *MoveReq) String() string            { return proto.CompactTextString(m) }
func (*MoveReq) ProtoMessage()               {}
func (*MoveReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func (m *MoveReq) GetPos() *Vector2 {
	if m != nil {
		return m.Pos
	}
	return nil
}

func (m *MoveReq) GetV() *Vector2 {
	if m != nil {
		return m.V
	}
	return nil
}

// 移动推送2106
type MovePush struct {
	Aoi              []*AOIPushItem `protobuf:"bytes,1,rep,name=aoi" json:"aoi,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *MovePush) Reset()                    { *m = MovePush{} }
func (m *MovePush) String() string            { return proto.CompactTextString(m) }
func (*MovePush) ProtoMessage()               {}
func (*MovePush) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

func (m *MovePush) GetAoi() []*AOIPushItem {
	if m != nil {
		return m.Aoi
	}
	return nil
}

// 攻击推送2107
type AttackPush struct {
	// 攻击方
	Attack *string `protobuf:"bytes,1,req,name=attack" json:"attack,omitempty"`
	// 被攻击方
	Attacked *string `protobuf:"bytes,2,req,name=attacked" json:"attacked,omitempty"`
	// 造成的伤害
	Damage *int32 `protobuf:"varint,3,req,name=damage" json:"damage,omitempty"`
	// 被攻击方当前生命值
	Hp               *int32 `protobuf:"varint,4,req,name=hp" json:"hp,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *AttackPush) Reset()                    { *m = AttackPush{} }
func (m *AttackPush) String() string            { return proto.CompactTextString(m) }
func (*AttackPush) ProtoMessage()               {}
func (*AttackPush) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

func (m *AttackPush) GetAttack() string {
	if m != nil && m.Attack != nil {
		return *m.Attack
	}
	return ""
}

func (m *AttackPush) GetAttacked() string {
	if m != nil && m.Attacked != nil {
		return *m.Attacked
	}
	return ""
}

func (m *AttackPush) GetDamage() int32 {
	if m != nil && m.Damage != nil {
		return *m.Damage
	}
	return 0
}

func (m *AttackPush) GetHp() int32 {
	if m != nil && m.Hp != nil {
		return *m.Hp
	}
	return 0
}

// 出生推送2108（玩家复活，刷怪、刷小兵，放水雷、导弹等）
type SpwanPush struct {
	Spwans           []*SpawnState `protobuf:"bytes,1,rep,name=spwans" json:"spwans,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *SpwanPush) Reset()                    { *m = SpwanPush{} }
func (m *SpwanPush) String() string            { return proto.CompactTextString(m) }
func (*SpwanPush) ProtoMessage()               {}
func (*SpwanPush) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12} }

func (m *SpwanPush) GetSpwans() []*SpawnState {
	if m != nil {
		return m.Spwans
	}
	return nil
}

// 死亡结算
type DeadSettlement struct {
	// 死亡者
	Dead *string `protobuf:"bytes,1,req,name=dead" json:"dead,omitempty"`
	// 击杀者
	Kill *string `protobuf:"bytes,2,req,name=kill" json:"kill,omitempty"`
	// 助攻者
	Assists []string `protobuf:"bytes,3,rep,name=assists" json:"assists,omitempty"`
	// 击杀者最后造成的伤害
	Damage           *int32 `protobuf:"varint,4,req,name=damage" json:"damage,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *DeadSettlement) Reset()                    { *m = DeadSettlement{} }
func (m *DeadSettlement) String() string            { return proto.CompactTextString(m) }
func (*DeadSettlement) ProtoMessage()               {}
func (*DeadSettlement) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{13} }

func (m *DeadSettlement) GetDead() string {
	if m != nil && m.Dead != nil {
		return *m.Dead
	}
	return ""
}

func (m *DeadSettlement) GetKill() string {
	if m != nil && m.Kill != nil {
		return *m.Kill
	}
	return ""
}

func (m *DeadSettlement) GetAssists() []string {
	if m != nil {
		return m.Assists
	}
	return nil
}

func (m *DeadSettlement) GetDamage() int32 {
	if m != nil && m.Damage != nil {
		return *m.Damage
	}
	return 0
}

// 死亡推送2109
type DeadPush struct {
	Death            []*DeadSettlement `protobuf:"bytes,1,rep,name=death" json:"death,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *DeadPush) Reset()                    { *m = DeadPush{} }
func (m *DeadPush) String() string            { return proto.CompactTextString(m) }
func (*DeadPush) ProtoMessage()               {}
func (*DeadPush) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{14} }

func (m *DeadPush) GetDeath() []*DeadSettlement {
	if m != nil {
		return m.Death
	}
	return nil
}

// 结束结算
type EndSettlement struct {
	// 实体id
	Entityid *string `protobuf:"bytes,1,req,name=entityid" json:"entityid,omitempty"`
	// 击杀次数
	Kill *int32 `protobuf:"varint,2,req,name=kill" json:"kill,omitempty"`
	// 死亡次数
	Dead *int32 `protobuf:"varint,3,req,name=dead" json:"dead,omitempty"`
	// 助攻次数
	Assists          *int32 `protobuf:"varint,4,req,name=assists" json:"assists,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *EndSettlement) Reset()                    { *m = EndSettlement{} }
func (m *EndSettlement) String() string            { return proto.CompactTextString(m) }
func (*EndSettlement) ProtoMessage()               {}
func (*EndSettlement) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{15} }

func (m *EndSettlement) GetEntityid() string {
	if m != nil && m.Entityid != nil {
		return *m.Entityid
	}
	return ""
}

func (m *EndSettlement) GetKill() int32 {
	if m != nil && m.Kill != nil {
		return *m.Kill
	}
	return 0
}

func (m *EndSettlement) GetDead() int32 {
	if m != nil && m.Dead != nil {
		return *m.Dead
	}
	return 0
}

func (m *EndSettlement) GetAssists() int32 {
	if m != nil && m.Assists != nil {
		return *m.Assists
	}
	return 0
}

// 结束推送2110
type OverPush struct {
	// 胜利的阵营
	Camp *int32 `protobuf:"varint,1,req,name=camp" json:"camp,omitempty"`
	// 红色方详情
	Red []*EndSettlement `protobuf:"bytes,2,rep,name=red" json:"red,omitempty"`
	// 蓝色方详情
	Blue             []*EndSettlement `protobuf:"bytes,3,rep,name=blue" json:"blue,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *OverPush) Reset()                    { *m = OverPush{} }
func (m *OverPush) String() string            { return proto.CompactTextString(m) }
func (*OverPush) ProtoMessage()               {}
func (*OverPush) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{16} }

func (m *OverPush) GetCamp() int32 {
	if m != nil && m.Camp != nil {
		return *m.Camp
	}
	return 0
}

func (m *OverPush) GetRed() []*EndSettlement {
	if m != nil {
		return m.Red
	}
	return nil
}

func (m *OverPush) GetBlue() []*EndSettlement {
	if m != nil {
		return m.Blue
	}
	return nil
}

func init() {
	proto.RegisterType((*Vector2)(nil), "protomsg.Vector2")
	proto.RegisterType((*AOI)(nil), "protomsg.AOI")
	proto.RegisterType((*AOIPushItem)(nil), "protomsg.AOIPushItem")
	proto.RegisterType((*SpawnState)(nil), "protomsg.SpawnState")
	proto.RegisterType((*CreateFightReq)(nil), "protomsg.create_fight_req")
	proto.RegisterType((*CreateFightAck)(nil), "protomsg.create_fight_ack")
	proto.RegisterType((*JoinFightReq)(nil), "protomsg.join_fight_req")
	proto.RegisterType((*JoinFightAck)(nil), "protomsg.join_fight_ack")
	proto.RegisterType((*JoinFightPush)(nil), "protomsg.join_fight_push")
	proto.RegisterType((*MoveReq)(nil), "protomsg.move_req")
	proto.RegisterType((*MovePush)(nil), "protomsg.move_push")
	proto.RegisterType((*AttackPush)(nil), "protomsg.attack_push")
	proto.RegisterType((*SpwanPush)(nil), "protomsg.spwan_push")
	proto.RegisterType((*DeadSettlement)(nil), "protomsg.DeadSettlement")
	proto.RegisterType((*DeadPush)(nil), "protomsg.dead_push")
	proto.RegisterType((*EndSettlement)(nil), "protomsg.EndSettlement")
	proto.RegisterType((*OverPush)(nil), "protomsg.over_push")
}

var fileDescriptor1 = []byte{
	// 567 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x53, 0x4f, 0x6f, 0xd3, 0x4e,
	0x10, 0x95, 0xed, 0xb8, 0x4d, 0x26, 0xbf, 0xe6, 0x07, 0xab, 0x02, 0x16, 0x12, 0xa2, 0x5a, 0x84,
	0xf8, 0x57, 0xe5, 0x50, 0x71, 0x02, 0x81, 0x84, 0x04, 0x12, 0x39, 0x51, 0x6d, 0x24, 0xae, 0xd1,
	0x92, 0x2c, 0x89, 0xdb, 0x38, 0x36, 0xde, 0x4d, 0xd2, 0x7c, 0x04, 0xbe, 0x35, 0xb3, 0xb3, 0xeb,
	0xd8, 0xa9, 0x48, 0xca, 0xc9, 0xf3, 0x76, 0xdf, 0xcc, 0xbe, 0x37, 0x33, 0x86, 0xee, 0xcf, 0x74,
	0x3a, 0x33, 0xfd, 0xa2, 0xcc, 0x4d, 0xce, 0xda, 0xf4, 0xc9, 0xf4, 0x94, 0x3f, 0x87, 0xe3, 0xef,
	0x6a, 0x6c, 0xf2, 0xf2, 0x82, 0xfd, 0x07, 0xc1, 0x4d, 0x12, 0x9c, 0x85, 0x2f, 0x43, 0x11, 0xdc,
	0x58, 0xb4, 0x49, 0x42, 0x87, 0x36, 0x7c, 0x04, 0xd1, 0xa7, 0x6f, 0x03, 0xc6, 0xa0, 0x65, 0xd2,
	0x4c, 0x11, 0x2b, 0x12, 0x14, 0xb3, 0x67, 0x10, 0x15, 0xb9, 0x26, 0x6a, 0xf7, 0xe2, 0x7e, 0xbf,
	0xaa, 0xdc, 0xf7, 0x65, 0x85, 0xbd, 0x65, 0x4f, 0x21, 0x58, 0x25, 0xd1, 0x3e, 0x4a, 0xb0, 0xe2,
	0x5f, 0xa1, 0x8b, 0x0f, 0x5c, 0x2e, 0xf5, 0x6c, 0x60, 0x54, 0xc6, 0x1e, 0x43, 0x5b, 0x2d, 0x4c,
	0x6a, 0x36, 0xe9, 0x84, 0x1e, 0xeb, 0x88, 0x2d, 0x66, 0x4f, 0x20, 0xcc, 0xaa, 0xf7, 0x4e, 0xea,
	0x62, 0x98, 0x2e, 0xf0, 0x82, 0xff, 0x0e, 0x00, 0x86, 0x85, 0x5c, 0x2f, 0x86, 0x46, 0x1a, 0x45,
	0x92, 0x37, 0x85, 0x93, 0x1c, 0x0b, 0x8a, 0x77, 0xaa, 0x87, 0x7f, 0xad, 0x1e, 0xed, 0xa9, 0xce,
	0x4e, 0x21, 0x2e, 0x95, 0x1e, 0x4c, 0x92, 0xd6, 0x59, 0x80, 0xf5, 0x1c, 0x60, 0x0f, 0xe1, 0x68,
	0xa9, 0x55, 0x89, 0xc7, 0x31, 0x1d, 0x7b, 0xc4, 0xcf, 0xe1, 0xde, 0xb8, 0x54, 0x28, 0x63, 0x44,
	0xdd, 0x1f, 0x95, 0xea, 0x17, 0x4b, 0xe0, 0x98, 0xc0, 0xd6, 0x59, 0x05, 0x39, 0xbb, 0xc5, 0x96,
	0xe3, 0x6b, 0xfe, 0x11, 0x7a, 0x57, 0x79, 0xba, 0xf8, 0x97, 0xfc, 0xad, 0xd5, 0xb0, 0xb6, 0x7a,
	0x2b, 0x1f, 0x2b, 0xb2, 0x73, 0x38, 0xd2, 0xb6, 0x3d, 0x1a, 0xd3, 0x23, 0x34, 0x79, 0x5a, 0x9b,
	0xac, 0xdb, 0x26, 0x3c, 0x87, 0x7f, 0x80, 0xff, 0x1b, 0xf9, 0x05, 0xce, 0x87, 0xbd, 0x86, 0x98,
	0x2e, 0xe9, 0xf9, 0x7d, 0xf9, 0x8e, 0xc2, 0x2f, 0xa1, 0x9d, 0xe5, 0x2b, 0x45, 0xc2, 0xfd, 0xa2,
	0x44, 0x77, 0x2f, 0x4a, 0xeb, 0xc0, 0xa2, 0xbc, 0x85, 0x0e, 0x55, 0x24, 0x29, 0x2f, 0x20, 0x92,
	0x79, 0xea, 0x8d, 0x3c, 0xd8, 0x99, 0x56, 0xb5, 0x4a, 0xc2, 0x32, 0x78, 0x0a, 0x5d, 0x69, 0x0c,
	0xda, 0x77, 0x79, 0x38, 0x2f, 0x07, 0x7d, 0x0b, 0x3d, 0xb2, 0x8b, 0xe1, 0x22, 0xb5, 0x5d, 0x8c,
	0x0a, 0xdb, 0x9c, 0x89, 0xcc, 0xe4, 0x54, 0x91, 0x03, 0x9c, 0xb1, 0x43, 0xac, 0x07, 0xe1, 0xac,
	0x20, 0xc9, 0xb1, 0xc0, 0x88, 0xbf, 0x03, 0xd0, 0xc5, 0x5a, 0x2e, 0xdc, 0x4b, 0xd4, 0x6d, 0x44,
	0x77, 0x76, 0xdb, 0x72, 0xf8, 0x15, 0xf4, 0x3e, 0x2b, 0x39, 0x19, 0x2a, 0x63, 0xe6, 0x2a, 0xc3,
	0x9d, 0xb4, 0x33, 0x9d, 0xe0, 0x89, 0xd7, 0x49, 0xb1, 0x3d, 0xbb, 0x4e, 0xe7, 0x73, 0xaf, 0x90,
	0x62, 0xbb, 0x15, 0x52, 0xeb, 0x54, 0x1b, 0xdb, 0xe0, 0xc8, 0x6e, 0x85, 0x87, 0x0d, 0xdd, 0xad,
	0xa6, 0x6e, 0xfe, 0x1e, 0x3a, 0xb6, 0x9a, 0x93, 0xd9, 0x87, 0x18, 0x81, 0x99, 0x79, 0x95, 0x49,
	0xad, 0x72, 0x57, 0x8f, 0x70, 0x34, 0x9e, 0xc1, 0xc9, 0x97, 0x45, 0x53, 0xe7, 0xa1, 0x1f, 0xb6,
	0xa9, 0x37, 0xf6, 0x7a, 0x2b, 0x5f, 0xae, 0x97, 0xce, 0x57, 0xc3, 0x83, 0x93, 0x5a, 0x41, 0xbe,
	0x86, 0x0e, 0xce, 0xbc, 0x74, 0x5a, 0x31, 0x75, 0x2c, 0xb3, 0xa2, 0xfa, 0xa3, 0x6d, 0xcc, 0x5e,
	0x41, 0x54, 0xd2, 0xcc, 0xac, 0xfa, 0x47, 0xb5, 0xfa, 0x1d, 0x91, 0xc2, 0x72, 0xd8, 0x1b, 0x68,
	0xfd, 0x98, 0x2f, 0x15, 0xb5, 0xe9, 0x00, 0x97, 0x48, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x60,
	0x11, 0xd5, 0x07, 0x36, 0x05, 0x00, 0x00,
}
