// Code generated by protoc-gen-go.
// source: game.proto
// DO NOT EDIT!

package protomsg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 广播测试2000
type TestReq struct {
	Test             []byte `protobuf:"bytes,1,req,name=test" json:"test,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *TestReq) Reset()                    { *m = TestReq{} }
func (m *TestReq) String() string            { return proto.CompactTextString(m) }
func (*TestReq) ProtoMessage()               {}
func (*TestReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *TestReq) GetTest() []byte {
	if m != nil {
		return m.Test
	}
	return nil
}

// 广播测试返回2001
type TestAck struct {
	Test             []byte `protobuf:"bytes,1,req,name=test" json:"test,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *TestAck) Reset()                    { *m = TestAck{} }
func (m *TestAck) String() string            { return proto.CompactTextString(m) }
func (*TestAck) ProtoMessage()               {}
func (*TestAck) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *TestAck) GetTest() []byte {
	if m != nil {
		return m.Test
	}
	return nil
}

// 广播测试推送2002
type TestPush struct {
	Test             []byte `protobuf:"bytes,1,req,name=test" json:"test,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *TestPush) Reset()                    { *m = TestPush{} }
func (m *TestPush) String() string            { return proto.CompactTextString(m) }
func (*TestPush) ProtoMessage()               {}
func (*TestPush) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *TestPush) GetTest() []byte {
	if m != nil {
		return m.Test
	}
	return nil
}

func init() {
	proto.RegisterType((*TestReq)(nil), "protomsg.test_req")
	proto.RegisterType((*TestAck)(nil), "protomsg.test_ack")
	proto.RegisterType((*TestPush)(nil), "protomsg.test_push")
}

var fileDescriptor2 = []byte{
	// 87 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x4f, 0xcc, 0x4d,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0xb9, 0xc5, 0xe9, 0x4a, 0x72, 0x5c,
	0x1c, 0x25, 0xa9, 0xc5, 0x25, 0xf1, 0x45, 0xa9, 0x85, 0x42, 0x42, 0x5c, 0x2c, 0x20, 0xb6, 0x04,
	0xa3, 0x02, 0x93, 0x06, 0x4f, 0x10, 0x98, 0x0d, 0x97, 0x4f, 0x4c, 0xce, 0xc6, 0x2a, 0x2f, 0xcf,
	0xc5, 0x09, 0x96, 0x2f, 0x28, 0x2d, 0xce, 0xc0, 0xa6, 0x00, 0x10, 0x00, 0x00, 0xff, 0xff, 0x9a,
	0x77, 0xb1, 0x8a, 0x77, 0x00, 0x00, 0x00,
}
